import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillGithub, AiFillInstagram } from "react-icons/ai";
import Image from "next/image";
import jp from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Pablo Jimenez Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white px-10 md:px-20 lg:px-40 dark:bg-background-dm">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className=" text-xl font-burtons dark:text-headlines-dm">
              Developed by JP
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl dark:text-headlines-dm"
                />
              </li>
              <li>
                <a
                  className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className=" text-center p-10">
            <h2 className=" text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Juan Pablo Jimenez
            </h2>
            <h3 className=" text-2xl py-2 md:text-3xl dark:text-headlines-dm ">
              Developer and designer.
            </h3>
            <p className=" text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-p-dm">
              Lorem ipsum dolor sit amet consectetur, adipisicing elit.
              Laudantium dolore assumenda eos cum dignissimos repellat labore
              similique quia error! Doloremque totam nihil accusantium
              voluptatum. Quisquam consectetur inventore dolorem deleniti et!
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-teal-500">
            <AiFillLinkedin />
            <AiFillGithub />
            <AiFillInstagram />
          </div>
          <div className=" relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 my-20 overflow-hidden md:h-96 md:w-96">
            <Image src={jp} layout="fill" objectFit="cover" />
          </div>
        </section>

        <section>
          <div>
            <h3 className=" text-3xl py-1 dark:text-headlines-dm">
              Services I offer
            </h3>
            <p className=" text-md py-2 leading-8 text-gray-80 dark:text-p-dm">
              Lorem ipsum dolor sit amet consectetur, adipisicing elit.
              Consequuntur amet dignissimos fugiat ratione accusamus quae{" "}
              <span className=" text-teal-500">agencies</span> consulted for{" "}
              <span className=" text-teal-500">
                Hexaware and Lennox International
              </span>{" "}
              Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi
              veniam commodi ratione
            </p>
            <p className=" text-md py-2 leading-8 text-gray-800 dark:text-p-dm">
              Lorem, ipsum dolor sit amet consectetur adipisicing elit
            </p>
          </div>
          <div className=" lg:flex justify-center gap-10">
            <div className=" text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={design} width={100} height={100} />
              <h3 className=" text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className=" py-2">
                {" "}
                Creating elegant designs suited for your needs.
              </p>
              <h4 className=" py-4 text-teal-600">Design tools I use</h4>
              <p className=" text-gray-800 py-1">Figma</p>
              <p className=" text-gray-800 py-1">Photoshop</p>
            </div>
            <div className=" text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={code} width={100} height={100} />
              <h3 className=" text-lg font-medium pt-8 pb-2">Code</h3>
              <p className=" py-2">
                {" "}
                Creating elegant designs suited for your needs.
              </p>
              <h4 className=" py-4 text-teal-600">Coding languages I use</h4>
              <p className=" text-gray-800 py-1">JavaScript</p>
              <p className=" text-gray-800 py-1">Photoshop</p>
            </div>
            <div className=" text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={consulting} width={100} height={100} />
              <h3 className=" text-lg font-medium pt-8 pb-2">Comprometido</h3>
              <p className=" py-2">
                {" "}
                Creating elegant designs suited for your needs.
              </p>
              <h4 className=" py-4 text-teal-600">Design tools I use</h4>
              <p className=" text-gray-800 py-1">Figma</p>
              <p className=" text-gray-800 py-1">Photoshop</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className=" text-3xl py-1">Portfolio</h3>
            <p className=" text-md py-2 leading-8 text-gray-80">
              Lorem ipsum dolor sit amet consectetur, adipisicing elit.
              Consequuntur amet dignissimos fugiat ratione accusamus quae{" "}
              <span className=" text-teal-500">agencies</span> consulted for{" "}
              <span className=" text-teal-500">
                Hexaware and Lennox International
              </span>{" "}
              Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi
              veniam commodi ratione
            </p>
            <p className=" text-md py-2 leading-8 text-gray-800">
              Lorem, ipsum dolor sit amet consectetur adipisicing elit
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className=" basis-1/3 flex-1">
              <Image
                src={web1}
                className=" rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className=" basis-1/3 flex-1">
              <Image
                src={web2}
                className=" rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className=" basis-1/3 flex-1">
              <Image
                src={web3}
                className=" rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className=" basis-1/3 flex-1">
              <Image
                src={web4}
                className=" rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className=" basis-1/3 flex-1">
              <Image
                src={web5}
                className=" rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className=" basis-1/3 flex-1">
              <Image
                src={web6}
                className=" rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
